### ISSUE TITLE
On Android 10 not working fully

### ISSUE THREAD

**Issue by JayaKrishnaKruthick** [ppawel/twitter-ad-eater#1]
My device: Redmi Note 7
ROM: MIUI.eu 
Android: 10
Using Lsposed
The module seems to working fine but I'm seeing at least one promotional tweet in the timeline wherever I open the app which are later disappeared.
Also whenever I go to a trending topic for the first time I see a promotional tweet if I go back and revisit the same trending topic again the promotional tweet are 
gone.
And I still see the stories in timeline.
Attaching all the screenshots of it.
Please provide support and updates to this module whenever need and fix the bugs
![IMG_20210329_075415](https://user-images.githubusercontent.com/81535995/112781244-11872480-9068-11eb-87c7-81f3222e49df.jpg)
![IMG_20210329_075253](https://user-images.githubusercontent.com/81535995/112781257-15b34200-9068-11eb-96f4-41e2a770b673.jpg)
![Screenshot_2021-03-29-03-21-17-285_com twitter android](https://user-images.githubusercontent.com/81535995/112781261-177d0580-9068-11eb-84bf-50c09e423086.jpg)
![Screenshot_2021-03-29-03-20-53-225_com twitter android](https://user-images.githubusercontent.com/81535995/112781292-2499f480-9068-11eb-8c34-b8736c17c780.jpg)
![Screenshot_2021-03-29-03-15-53-910_com twitter android](https://user-images.githubusercontent.com/81535995/112781303-2cf22f80-9068-11eb-870b-800d5367d8dc.jpg)
![Screenshot_2021-03-29-03-03-51-020_com twitter android](https://user-images.githubusercontent.com/81535995/112781341-4004ff80-9068-11eb-9f22-5cc337acf9ac.jpg)
![Screenshot_2021-03-29-02-58-02-501_com twitter android](https://user-images.githubusercontent.com/81535995/112781362-48f5d100-9068-11eb-8689-5457f3378ada.jpg)

**Comment by ppawel** [comment]
Thanks for the report and the screenshots. I am testing some improvements currently, stay tuned for the new version.

**Comment by JayaKrishnaKruthick** [comment]
I just updated to the latest version and the stories section is still present in the timeline, now i can say that the ads in the trending topics are still there revisiting the trending topics again fixes it but in the timeline the ads are still present it's as if it's not blocking ads in timeline I'm going back to previous version in the previous version I just used to see  less ads
![IMG_20210330_091145](https://user-images.githubusercontent.com/81535995/112930995-ec161b80-9138-11eb-9593-9f1027b14b3f.jpg)
![IMG_20210330_091209](https://user-images.githubusercontent.com/81535995/112931008-ee787580-9138-11eb-9a46-f468ce77d0ea.jpg)
![IMG_20210330_091221](https://user-images.githubusercontent.com/81535995/112931013-efa9a280-9138-11eb-9fe9-0692c116e71a.jpg)
Also is this intentional the latest version having the same version number as the previous and having different APK signature I had to uninstall the previous one to install this
![Screenshot_2021-03-30-08-03-31-909_com miui packageinstaller](https://user-images.githubusercontent.com/81535995/112931128-2aabd600-9139-11eb-9ba2-5c387f8339ab.jpg)

**Comment by ppawel** [comment]
The issue with the version is my mistake, I will fix that with the next one.

About the ads in the timeline, hmm, I can't reproduce it, will try to add one configuration parameter that could help in the next version.

**Comment by JayaKrishnaKruthick** [comment]
Is there anything which I can help you with like any logs that you need
Lsposed logs 
2021-03-30 09:49:57.057 I/com.twitter.android(26386-26386): NOM NOM NOM com.twitter.android
2021-03-30 09:49:57.057 I/com.twitter.android(26386-26386): Twitter app loaded... (package = com.twitter.android)

**Comment by ppawel** [comment]
You could check logcat logs for "TwitterAdEater" or for "Twitter" in general and see if there are any errors when you use the timeline for example.

**Comment by JayaKrishnaKruthick** [comment]
[2021-03-30-18-11-25[1].txt](https://github.com/ppawel/twitter-ad-eater/files/6229146/2021-03-30-18-11-25.1.txt)
These logs are with the initial release v1.0 let me know if I should take logs with the latest version. i dont know how to take logs but i tried using matlog ran recording opened twitter feed and scrolled and interacted with promotional tweets again repeated the same please take a look if not please let me know how to take logs so i can take

**Comment by JayaKrishnaKruthick** [comment]
[V1.1 2021-03-30-20-14-08.txt](https://github.com/ppawel/twitter-ad-eater/files/6229882/V1.1.2021-03-30-20-14-08.txt)
These are the logs with the latest release V1.1

**Comment by ppawel** [comment]
If you want, you can try using this development version - https://github.com/ppawel/twitter-ad-eater/actions/runs/706125428#artifacts

This contains a lot of logging output so I don't recommend using it permanently. You can capture logs using logcat for example.

**Comment by JayaKrishnaKruthick** [comment]
> If you want, you can try using this development version - https://github.com/ppawel/twitter-ad-eater/actions/runs/706125428#artifacts
> 
> This contains a lot of logging output so I don't recommend using it permanently. You can capture logs using logcat for example.

I signed the app using lucky patcher and installed it,this version seems to be working well I don't seem to see any ads .But the stories section is still present.let me know if you need the logs for now I'm uninstalling and will be waiting for the release.

**Comment by ppawel** [comment]
OK, thanks for the feedback. Next release will be signed, I have not had time to set up the signing process yet.

Regarding stories, do you mean the round things at the top of the timeline? If yes, then this is on the TODO list currently.

**Comment by JayaKrishnaKruthick** [comment]
> If you want, you can try using this development version - https://github.com/ppawel/twitter-ad-eater/actions/runs/706125428#artifacts
> 
    
I donno if this is related or not but I completely removed the module to say I completely removed riru and lsposed but still I'm not seeing any ads in twitter even tried reinstalling twitter is this normal.it's as if the mods still working or maybe I donno

**Comment by ppawel** [comment]
Hmm, strange, when you remove the module or even disable it, then there is no hooks anymore, so the ads would show up again...
